adapter: mysql

development:
   host: dewdfglp01669
   port: 3306
   username: franky
   password: NewYorkNewYork
   database: s3lcontrol

production:
  host: dewdfglp01669
  port: 3306
  username: franky
  password: NewYorkNewYork
  database: s3lcontrol